default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch # prevent direct commits to main branch
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: local
    hooks:
      - id: docs-lint
        name: Check documentation format
        entry: nox -s docs-lint
        language: system
        types: [rst, markdown]
        pass_filenames: false
        stages: [pre-commit]
        # Only run when docs related files are changed
        files: |
          (?x)^(
            docs/.*|
            .*\.rst|
            .*\.md|
            nox_actions/docs\.py|
            pyproject\.toml
          )$
