name: Upload Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        fetch-depth: 0
    
    - name: Get tag
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Get previous tag
      id: previoustag
      run: |
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)
        echo "tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install -r requirements-dev.txt
        poetry --version
        poetry build
    
    # Note that we don't need credentials.
    # We rely on https://docs.pypi.org/trusted-publishers/.
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist
    
    - name: Generate changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter-author: (loonghao|dependabot|renovate\\[bot\\]|renovate-bot|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d+\.\d+\.\d+'
        fromTag: ${{ steps.previoustag.outputs.tag }}
        toTag: ${{ steps.tag.outputs.tag }}
        template: |
          ## 🐛 Bug Fixes
          {{fix}}
          ## ✨ Features
          {{feat}}
          ## 🔄 Improvements
          {{refactor,perf,clean}}
          ## 🛠️ Maintenance
          {{chore,style,ci||🔶 Nothing to report}}
          ## 📝 Documentation
          {{docs||🔶 No documentation changes}}
          ## 🧪 Tests
          {{test||🔶 No test changes}}
          ## Other Changes
          {{__unknown__||🔶 No other changes}}
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.tag.outputs.tag }}
        tag: ${{ steps.tag.outputs.tag }}
        artifacts: "dist/*"
        body: |
          ## Release ${{ steps.tag.outputs.tag }}
          
          ${{ steps.changelog.outputs.compareurl }}
          
          ### What's Changed
          
          ${{ steps.changelog.outputs.changelog }}
          
          ### Assets
          
          📦 Python package is available on [PyPI](https://pypi.org/project/persistent-ssh-agent/)
        draft: false
        prerelease: false
